/*
 * JS for Graph generated by Tiggzi
 *
 * Created on: Monday, April 15, 2013, 05:37:07 PM (PDT)
 */
/************************************
 * JS API provided by Exadel Tiggzi  *
 ************************************/
/* Setting project environment indicator */
Tiggzi.env = "bundle";
Tiggzi.getProjectGUID = function() {
    return '45d66a9c-4dcc-4df4-9bc6-0d38590e8129';
}
Tiggzi.getTargetPlatform = function() {
    return '0';
}

function navigateTo(outcome, useAjax) {
    Tiggzi.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Tiggzi.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Tiggzi.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Tiggzi.setDetailContent(pageUrl);
}
/**********************
 * SECURITY CONTEXTS  *
 **********************/
/*******************************
 *      SERVICE SETTINGS        *
 ********************************/
var StackMobDatabaseSettings1 = {
    "stackMobPublicKey": "dc66e11c-d4b7-40a3-8511-53ebfda982df"
}
var StackMobDatabaseSettings4 = {
    "stackMobPublicKey": "dc66e11c-d4b7-40a3-8511-53ebfda982df"
}
var StackMobDatabaseSettings6 = {
    "stackMobPublicKey": "dc66e11c-d4b7-40a3-8511-53ebfda982df"
}
var StackMobDatabaseSettings5 = {
    "stackMobPublicKey": ""
}
var StackMobDatabaseSettings2 = {
    "stackMobPublicKey": ""
}
var StackMobDatabaseSettings3 = {
    "stackMobPublicKey": "dc66e11c-d4b7-40a3-8511-53ebfda982df"
}
var StackMobDatabaseSettings = {
    "stackMobPublicKey": "dc66e11c-d4b7-40a3-8511-53ebfda982df"
}
/*************************
 *      SERVICES          *
 *************************/
var StackMobSurveyPost = new Tiggr.RestService({
    'url': 'https://api.mob1.stackmob.com/survey',
    'dataType': 'json',
    'type': 'post',
    'contentType': 'application/json',
    'serviceSettings': StackMobDatabaseSettings4
});
var StackMobGet = new Tiggr.RestService({
    'url': 'https://api.mob1.stackmob.com/dprof/',
    'dataType': 'json',
    'type': 'get',
    'serviceSettings': StackMobDatabaseSettings1
});
var StackMobSurveyGet = new Tiggr.RestService({
    'url': 'https://api.mob1.stackmob.com/survey',
    'dataType': 'json',
    'type': 'get',
    'serviceSettings': StackMobDatabaseSettings6
});
var StackMobPut = new Tiggr.RestService({
    'url': 'https://api.mob1.stackmob.com/dprof/',
    'dataType': 'json',
    'type': 'put',
    'contentType': 'application/json',
});
var StackMobDatabase1 = new Tiggr.RestService({
    'url': 'https://api.mob1.stackmob.com/dprof',
    'dataType': 'json',
    'type': 'get',
    'serviceSettings': StackMobDatabaseSettings5
});
var StackMobGetCity = new Tiggr.RestService({
    'url': 'https://api.mob1.stackmob.com/dprof',
    'dataType': 'json',
    'type': 'get',
});
var StackMobPost = new Tiggr.RestService({
    'url': 'https://api.mob1.stackmob.com/dprof/',
    'dataType': 'json',
    'type': 'post',
    'contentType': 'application/json',
    'serviceSettings': StackMobDatabaseSettings
});
createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
Tiggzi.AppPages = [{
    "name": "Results",
    "location": "Results.html"
}, {
    "name": "Survey",
    "location": "Survey.html"
}, {
    "name": "Survey12",
    "location": "Survey12.html"
}, {
    "name": "Survey11",
    "location": "Survey11.html"
}, {
    "name": "Graph",
    "location": "Graph.html"
}, {
    "name": "Survey1",
    "location": "Survey1.html"
}, {
    "name": "Info",
    "location": "Info.html"
}];
j_160_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel39': 'j_164',
        'mobilepanel1': 'j_165',
        'mobilenavbar8': 'j_167',
        'surveybutton': 'j_168',
        'resultsbutton': 'j_169',
        'historybutton': 'j_170'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    Tiggr.CurrentScreen = 'j_160';
    /*************************
     * NONVISUAL COMPONENTS  *
     *************************/
    var datasources = [];
    // Tiggzi Push-notification registration service
    /************************
     * EVENTS AND HANDLERS  *
     ************************/
    j_160_beforeshow = function() {
        Tiggzi.CurrentScreen = 'j_160';
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }
    // screen onload
    screen_863E_onLoad = j_160_onLoad = function() {
        screen_863E_elementsExtraJS();
        j_160_windowEvents();
        screen_863E_elementsEvents();
    }
    // screen window events
    screen_863E_windowEvents = j_160_windowEvents = function() {
        $('#j_160').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });
    }
    // screen elements extra js
    screen_863E_elementsExtraJS = j_160_elementsExtraJS = function() {
        // screen (screen-863E) extra code
    }
    // screen elements handler
    screen_863E_elementsEvents = j_160_elementsEvents = function() {
        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });
        $('#j_166 [name="surveybutton"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    window.location = 'Survey.html';
                }
            },
        });
        $('#j_166 [name="resultsbutton"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    window.location = 'Results.html';
                }
            },
        });
    }
    $("#j_160").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        j_160_beforeshow();
    });
    if (runBeforeShow) {
        j_160_beforeshow();
    } else {
        j_160_onLoad();
    }
}
$("#j_160").die("pageinit").live("pageinit", function(event, ui) {
    Tiggzi.processSelectMenu($(this));
    j_160_js();
});