/*
 * JS for Info generated by Tiggzi
 *
 * Created on: Monday, April 15, 2013, 05:37:07 PM (PDT)
 */
/************************************
 * JS API provided by Exadel Tiggzi  *
 ************************************/
/* Setting project environment indicator */
Tiggzi.env = "bundle";
Tiggzi.getProjectGUID = function() {
    return '45d66a9c-4dcc-4df4-9bc6-0d38590e8129';
}
Tiggzi.getTargetPlatform = function() {
    return '0';
}

function navigateTo(outcome, useAjax) {
    Tiggzi.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Tiggzi.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Tiggzi.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Tiggzi.setDetailContent(pageUrl);
}
/**********************
 * SECURITY CONTEXTS  *
 **********************/
/*******************************
 *      SERVICE SETTINGS        *
 ********************************/
var StackMobDatabaseSettings1 = {
    "stackMobPublicKey": "dc66e11c-d4b7-40a3-8511-53ebfda982df"
}
var StackMobDatabaseSettings4 = {
    "stackMobPublicKey": "dc66e11c-d4b7-40a3-8511-53ebfda982df"
}
var StackMobDatabaseSettings6 = {
    "stackMobPublicKey": "dc66e11c-d4b7-40a3-8511-53ebfda982df"
}
var StackMobDatabaseSettings5 = {
    "stackMobPublicKey": ""
}
var StackMobDatabaseSettings2 = {
    "stackMobPublicKey": ""
}
var StackMobDatabaseSettings3 = {
    "stackMobPublicKey": "dc66e11c-d4b7-40a3-8511-53ebfda982df"
}
var StackMobDatabaseSettings = {
    "stackMobPublicKey": "dc66e11c-d4b7-40a3-8511-53ebfda982df"
}
/*************************
 *      SERVICES          *
 *************************/
var StackMobSurveyPost = new Tiggr.RestService({
    'url': 'https://api.mob1.stackmob.com/survey',
    'dataType': 'json',
    'type': 'post',
    'contentType': 'application/json',
    'serviceSettings': StackMobDatabaseSettings4
});
var StackMobGet = new Tiggr.RestService({
    'url': 'https://api.mob1.stackmob.com/dprof/',
    'dataType': 'json',
    'type': 'get',
    'serviceSettings': StackMobDatabaseSettings1
});
var StackMobSurveyGet = new Tiggr.RestService({
    'url': 'https://api.mob1.stackmob.com/survey',
    'dataType': 'json',
    'type': 'get',
    'serviceSettings': StackMobDatabaseSettings6
});
var StackMobPut = new Tiggr.RestService({
    'url': 'https://api.mob1.stackmob.com/dprof/',
    'dataType': 'json',
    'type': 'put',
    'contentType': 'application/json',
});
var StackMobDatabase1 = new Tiggr.RestService({
    'url': 'https://api.mob1.stackmob.com/dprof',
    'dataType': 'json',
    'type': 'get',
    'serviceSettings': StackMobDatabaseSettings5
});
var StackMobGetCity = new Tiggr.RestService({
    'url': 'https://api.mob1.stackmob.com/dprof',
    'dataType': 'json',
    'type': 'get',
});
var StackMobPost = new Tiggr.RestService({
    'url': 'https://api.mob1.stackmob.com/dprof/',
    'dataType': 'json',
    'type': 'post',
    'contentType': 'application/json',
    'serviceSettings': StackMobDatabaseSettings
});
createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
Tiggzi.AppPages = [{
    "name": "Results",
    "location": "Results.html"
}, {
    "name": "Survey",
    "location": "Survey.html"
}, {
    "name": "Survey12",
    "location": "Survey12.html"
}, {
    "name": "Survey11",
    "location": "Survey11.html"
}, {
    "name": "Graph",
    "location": "Graph.html"
}, {
    "name": "Survey1",
    "location": "Survey1.html"
}, {
    "name": "Info",
    "location": "Info.html"
}];
j_172_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel57': 'j_176',
        'mobilegrid14': 'j_177',
        'mobilegridcell35': 'j_178',
        'mobiletextinput2': 'j_179',
        'mobilegridcell36': 'j_180',
        'mobiletextinput3': 'j_181',
        'mobilelabel29': 'j_182',
        'mobiletextinput8': 'j_183',
        'mobilelabel30': 'j_184',
        'mobiletextinput9': 'j_185',
        'mobilelabel21': 'j_186',
        'mobileradiogroup13': 'j_187',
        'mobileradiobutton1': 'j_188',
        'mobileradiobutton2': 'j_189',
        'mobileradiobutton3': 'j_190',
        'mobileradiobutton7': 'j_191',
        'mobilelabel28': 'j_192',
        'mobiletextinput13': 'j_193',
        'mobilespacer1': 'j_194',
        'done': 'j_195'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    Tiggr.CurrentScreen = 'j_172';
    /*************************
     * NONVISUAL COMPONENTS  *
     *************************/
    var datasources = [];
    dprofpost = new Tiggr.DataSource(StackMobPost, {
        'onComplete': function(jqXHR, textStatus) {
            $t.refreshScreenFormElements("j_172");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [{
            'PATH': ['city'],
            'ID': '___local_storage___',
            'ATTR': 'cityname'
        }, {
            'PATH': ['dprof_id'],
            'ID': '___local_storage___',
            'ATTR': 'userid'
        }, {
            'PATH': ['numrooms'],
            'ID': '___local_storage___',
            'ATTR': 'numberofrooms'
        }, {
            'PATH': ['lname'],
            'ID': '___local_storage___',
            'ATTR': 'lastname'
        }, {
            'PATH': ['fname'],
            'ID': '___local_storage___',
            'ATTR': 'firstname'
        }, {
            'PATH': ['numcars'],
            'ID': '___local_storage___',
            'ATTR': 'numberofcars'
        }],
        'requestMapping': [{
            'PATH': ['X-StackMob-API-Key'],
            'HEADER': true,
            'ATTR': '{stackMobPublicKey}'
        }, {
            'PATH': ['Accept'],
            'HEADER': true,
            'ATTR': 'application/vnd.stackmob+json; version=0'
        }, {
            'PATH': ['fname'],
            'ID': 'mobiletextinput2',
            'ATTR': 'value'
        }, {
            'PATH': ['lname'],
            'ID': 'mobiletextinput3',
            'ATTR': 'value'
        }, {
            'PATH': ['city'],
            'ID': 'mobiletextinput8',
            'ATTR': 'value'
        }, {
            'PATH': ['numcars'],
            'ID': 'mobiletextinput9',
            'ATTR': 'value'
        }, {
            'PATH': ['cartype'],
            'ID': 'mobileradiogroup13',
            'ATTR': 'value'
        }]
    });
    datasources.push(dprofpost);
    dprofget = new Tiggr.DataSource(StackMobGet, {
        'onComplete': function(jqXHR, textStatus) {
            $t.refreshScreenFormElements("j_172");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [{
            'PATH': ['lname'],
            'ID': '___local_storage___',
            'ATTR': 'lastname'
        }, {
            'PATH': ['cartype'],
            'ID': '___local_storage___',
            'ATTR': 'typesofcars'
        }, {
            'PATH': ['dprof_id'],
            'ID': '___local_storage___',
            'ATTR': 'userid'
        }, {
            'PATH': ['numcars'],
            'ID': '___local_storage___',
            'ATTR': 'numberofcars'
        }, {
            'PATH': ['numrooms'],
            'ID': '___local_storage___',
            'ATTR': 'numberofrooms'
        }, {
            'PATH': ['city'],
            'ID': '___local_storage___',
            'ATTR': 'cityname'
        }, {
            'PATH': ['fname'],
            'ID': '___local_storage___',
            'ATTR': 'firstname'
        }],
        'requestMapping': [{
            'PATH': ['X-StackMob-API-Key'],
            'HEADER': true,
            'ATTR': 'dc66e11c-d4b7-40a3-8511-53ebfda982df'
        }, {
            'PATH': ['Accept'],
            'HEADER': true,
            'ATTR': 'application/vnd.stackmob+json; version=0'
        }, {
            'PATH': ['fname'],
            'ID': '___local_storage___',
            'ATTR': 'firstname'
        }, {
            'PATH': ['lname'],
            'ID': '___local_storage___',
            'ATTR': 'lastname'
        }, {
            'PATH': ['city'],
            'ID': '___local_storage___',
            'ATTR': 'cityname'
        }, {
            'PATH': ['numcars'],
            'ID': '___local_storage___',
            'ATTR': 'numberofcars'
        }, {
            'PATH': ['cartype'],
            'ID': '___local_storage___',
            'ATTR': 'typesofcars'
        }, {
            'PATH': ['numrooms'],
            'ID': '___local_storage___',
            'ATTR': 'numberofrooms'
        }, {
            'PATH': ['lname'],
            'ID': '___local_storage___',
            'ATTR': 'userid'
        }]
    });
    datasources.push(dprofget);
    // Tiggzi Push-notification registration service
    /************************
     * EVENTS AND HANDLERS  *
     ************************/
    j_172_beforeshow = function() {
        Tiggzi.CurrentScreen = 'j_172';
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }
    // screen onload
    screen_7C28_onLoad = j_172_onLoad = function() {
        screen_7C28_elementsExtraJS();
        j_172_windowEvents();
        screen_7C28_elementsEvents();
    }
    // screen window events
    screen_7C28_windowEvents = j_172_windowEvents = function() {
        $('#j_172').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });
        $('#j_172').bind({
            pageshow: function() {
                try {
                    dprofget.execute({})
                } catch (ex) {
                    console.log(ex.name + '  ' + ex.message);
                    hideSpinner();
                };
                setText('j_179', localStorage.getItem('firstname'));
                setText('j_181', localStorage.getItem('lastname'));
                setText('j_183', localStorage.getItem('cityname'));
                setText('j_185', localStorage.getItem('numberofcars'));
                setText('j_193', localStorage.getItem('numberofrooms'));
            },
        });
    }
    // screen elements extra js
    screen_7C28_elementsExtraJS = j_172_elementsExtraJS = function() {
        // screen (screen-7C28) extra code
    }
    // screen elements handler
    screen_7C28_elementsEvents = j_172_elementsEvents = function() {
        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });
        $('#j_175 [name="done"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    try {
                        dprofpost.execute({})
                    } catch (ex) {
                        console.log(ex.name + '  ' + ex.message);
                        hideSpinner();
                    };
                    Tiggr.navigateTo('Survey', {
                        transition: 'flip',
                        reverse: true
                    });
                }
            },
        });
    }
    $("#j_172").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        j_172_beforeshow();
    });
    if (runBeforeShow) {
        j_172_beforeshow();
    } else {
        j_172_onLoad();
    }
}
$("#j_172").die("pageinit").live("pageinit", function(event, ui) {
    Tiggzi.processSelectMenu($(this));
    j_172_js();
});