/*
 * JS for AddEventWhat generated by Tiggzi
 *
 * Created on: Monday, April 15, 2013, 05:30:39 PM (PDT)
 */
/************************************
 * JS API provided by Exadel Tiggzi  *
 ************************************/
/* Setting project environment indicator */
Tiggzi.env = "bundle";
Tiggzi.getProjectGUID = function() {
    return '46d01e13-5e39-4d93-81d0-c3d4c5617e10';
}
Tiggzi.getTargetPlatform = function() {
    return '0';
}

function navigateTo(outcome, useAjax) {
    Tiggzi.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Tiggzi.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Tiggzi.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Tiggzi.setDetailContent(pageUrl);
}
/**********************
 * SECURITY CONTEXTS  *
 **********************/
/*******************************
 *      SERVICE SETTINGS        *
 ********************************/
/*************************
 *      SERVICES          *
 *************************/
var GetToken = new Tiggr.RestService({
    'url': 'https://graph.facebook.com/oauth/access_token',
    'dataType': 'json',
    'type': 'get',
});
var RESTService = new Tiggr.RestService({
    'url': 'http://study-api.herokuapp.com/api/notices',
    'dataType': 'json',
    'type': 'post',
    'contentType': 'application/json',
});
var GetData = new Tiggr.RestService({
    'url': 'https://graph.facebook.com/me',
    'dataType': 'json',
    'type': 'get',
});
var Camera_service = new Tiggr.CameraService({});
createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
Tiggzi.AppPages = [{
    "name": "AddEventWhat",
    "location": "AddEventWhat.html"
}, {
    "name": "AddEventWhen",
    "location": "AddEventWhen.html"
}, {
    "name": "FinishedCreating",
    "location": "FinishedCreating.html"
}, {
    "name": "AddEventHow",
    "location": "AddEventHow.html"
}, {
    "name": "Result",
    "location": "Result.html"
}, {
    "name": "whatwhatwhat",
    "location": "whatwhatwhat.html"
}, {
    "name": "AddEventWho",
    "location": "AddEventWho.html"
}, {
    "name": "whowhowho",
    "location": "whowhowho.html"
}, {
    "name": "howhowhow1",
    "location": "howhowhow1.html"
}, {
    "name": "Login",
    "location": "Login.html"
}, {
    "name": "whenwhenwhen",
    "location": "whenwhenwhen.html"
}, {
    "name": "Home",
    "location": "Home.html"
}];
j_20_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel25': 'j_24',
        'mobiletextinput11': 'j_25',
        'mobilespacer15': 'j_26',
        'mobilelabel28': 'j_27',
        'mobiletextinput12': 'j_28',
        'mobilespacer18': 'j_29',
        'mobilelabel30': 'j_30',
        'mobiletextarea34': 'j_31',
        'mobilespacer21': 'j_32',
        'mobilebutton26': 'j_33',
        'mobilebutton27': 'j_34'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    Tiggr.CurrentScreen = 'j_20';
    /*************************
     * NONVISUAL COMPONENTS  *
     *************************/
    var datasources = [];
    // Tiggzi Push-notification registration service
    /************************
     * EVENTS AND HANDLERS  *
     ************************/
    j_20_beforeshow = function() {
        Tiggzi.CurrentScreen = 'j_20';
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }
    // screen onload
    screen_05F6_onLoad = j_20_onLoad = function() {
        screen_05F6_elementsExtraJS();
        j_20_windowEvents();
        screen_05F6_elementsEvents();
    }
    // screen window events
    screen_05F6_windowEvents = j_20_windowEvents = function() {
        $('#j_20').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });
    }
    // screen elements extra js
    screen_05F6_elementsExtraJS = j_20_elementsExtraJS = function() {
        // screen (screen-05F6) extra code
    }
    // screen elements handler
    screen_05F6_elementsEvents = j_20_elementsEvents = function() {
        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });
        $('#j_23 [name="mobiletextinput11"]').die().live({
            input: function() {
                localStorage.setItem('title', 'text');
            },
        });
        $('#j_23 [name="mobiletextinput12"]').die().live({
            input: function() {
                setVar_('subject', 'j_28', 'text', '', this);
            },
        });
        $('#j_23 [name="mobiletextarea34"]').die().live({
            input: function() {
                setVar_('description', 'j_31', 'text', '', this);
            },
        });
        $('#j_23 [name="mobilebutton26"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('AddEventHow', {
                        reverse: false
                    });
                }
            },
        });
        $('#j_23 [name="mobilebutton27"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('Home', {
                        reverse: false
                    });
                    Tiggr.navigateTo('Home', {
                        reverse: false
                    });
                }
            },
        });
    }
    $("#j_20").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        j_20_beforeshow();
    });
    if (runBeforeShow) {
        j_20_beforeshow();
    } else {
        j_20_onLoad();
    }
}
$("#j_20").die("pageinit").live("pageinit", function(event, ui) {
    Tiggzi.processSelectMenu($(this));
    j_20_js();
});