/*
 * JS for AddEventWhen generated by Tiggzi
 *
 * Created on: Monday, April 15, 2013, 05:30:39 PM (PDT)
 */
/************************************
 * JS API provided by Exadel Tiggzi  *
 ************************************/
/* Setting project environment indicator */
Tiggzi.env = "bundle";
Tiggzi.getProjectGUID = function() {
    return '46d01e13-5e39-4d93-81d0-c3d4c5617e10';
}
Tiggzi.getTargetPlatform = function() {
    return '0';
}

function navigateTo(outcome, useAjax) {
    Tiggzi.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Tiggzi.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Tiggzi.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Tiggzi.setDetailContent(pageUrl);
}
/**********************
 * SECURITY CONTEXTS  *
 **********************/
/*******************************
 *      SERVICE SETTINGS        *
 ********************************/
/*************************
 *      SERVICES          *
 *************************/
var GetToken = new Tiggr.RestService({
    'url': 'https://graph.facebook.com/oauth/access_token',
    'dataType': 'json',
    'type': 'get',
});
var RESTService = new Tiggr.RestService({
    'url': 'http://study-api.herokuapp.com/api/notices',
    'dataType': 'json',
    'type': 'post',
    'contentType': 'application/json',
});
var GetData = new Tiggr.RestService({
    'url': 'https://graph.facebook.com/me',
    'dataType': 'json',
    'type': 'get',
});
var Camera_service = new Tiggr.CameraService({});
createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
Tiggzi.AppPages = [{
    "name": "AddEventWhat",
    "location": "AddEventWhat.html"
}, {
    "name": "AddEventWhen",
    "location": "AddEventWhen.html"
}, {
    "name": "FinishedCreating",
    "location": "FinishedCreating.html"
}, {
    "name": "AddEventHow",
    "location": "AddEventHow.html"
}, {
    "name": "Result",
    "location": "Result.html"
}, {
    "name": "whatwhatwhat",
    "location": "whatwhatwhat.html"
}, {
    "name": "AddEventWho",
    "location": "AddEventWho.html"
}, {
    "name": "whowhowho",
    "location": "whowhowho.html"
}, {
    "name": "howhowhow1",
    "location": "howhowhow1.html"
}, {
    "name": "Login",
    "location": "Login.html"
}, {
    "name": "whenwhenwhen",
    "location": "whenwhenwhen.html"
}, {
    "name": "Home",
    "location": "Home.html"
}];
j_0_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel4': 'j_4',
        'mobiledatepicker2': 'j_5',
        'mobilelabel16': 'j_6',
        'mobiletextinput8': 'j_7',
        'mobiletextinput9': 'j_8',
        'mobilelabel5': 'j_9',
        'loc': 'j_10',
        'mobilebutton4': 'j_11',
        'map': 'j_12',
        'marker1': 'j_13',
        'markeroptions2': 'j_14',
        'mobilebutton28': 'j_15',
        'mobilebutton39': 'j_16',
        'mobilebutton29': 'j_17'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    Tiggr.CurrentScreen = 'j_0';
    /*************************
     * NONVISUAL COMPONENTS  *
     *************************/
    var datasources = [];
    // Tiggzi Push-notification registration service
    /************************
     * EVENTS AND HANDLERS  *
     ************************/
    j_0_beforeshow = function() {
        Tiggzi.CurrentScreen = 'j_0';
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }
    // screen onload
    screen_8DD2_onLoad = j_0_onLoad = function() {
        screen_8DD2_elementsExtraJS();
        initialize();
        j_0_windowEvents();
        screen_8DD2_elementsEvents();
    }
    // screen window events
    screen_8DD2_windowEvents = j_0_windowEvents = function() {
        $('#j_0').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });
        $('#j_0').bind({
            swipeleft: function() {
                Tiggr.navigateTo('AddEventHow', {
                    transition: 'slide',
                    reverse: false
                });
            },
            swiperight: function() {
                Tiggr.navigateTo('AddEventWhat', {
                    transition: 'slide',
                    reverse: false
                });
            },
        });
    }
    // screen elements extra js
    screen_8DD2_elementsExtraJS = j_0_elementsExtraJS = function() {
        // screen (screen-8DD2) extra code
        /* mobiledatepicker2 */
        mobiledatepicker1_selector = "#j_5";
        mobiledatepicker1_dataPickerOptions = {
            dateFormat: "mm/dd/yy",
            firstDay: 0,
            dayNamesMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
            monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
            showOtherMonths: true
        };
        Tiggzi.__registerComponent('mobiledatepicker2', new Tiggzi.TiggziMobileDatePickerComponent("j_5", mobiledatepicker1_dataPickerOptions)); /* map */
        var map_options = {
            markerSourceName: "map_markers",
            latitude: "37.443",
            longitude: "-122.158",
            address: "",
            zoom: 10,
            showLocationMarker: false
        }
        Tiggzi.__registerComponent('map', new Tiggzi.TiggziMapComponent("map", map_options));
        $("[name='map']").closest("[data-role='page']").bind({
            pageshow: function() {
                if (Tiggzi('map') != undefined) {
                    Tiggzi('map').refresh();
                }
            }
        }); /* markeroptions2 */
        $("#j_14").attr("reRender", "map");
    }
    // screen elements handler
    screen_8DD2_elementsEvents = j_0_elementsEvents = function() {
        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });
        $('#j_3 [name="mobiledatepicker2"]').die().live({
            input: function() {
                setVar_('date', 'j_5', 'dateFormat', '', this);
            },
        });
        $('#j_3 [name="mobilebutton4"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    var sourceAddress = Tiggr("loc").val();
                    var map = Tiggr("map").gmap;
                    var marker = Tiggr("marker1");
                    updateAddress(sourceAddress, map, marker);
                }
            },
        });
        $('#j_3 [name="mobilebutton28"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('AddEventWho', {
                        reverse: false
                    });
                }
            },
        });
        $('#j_3 [name="mobilebutton39"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('Home', {
                        reverse: false
                    });
                }
            },
        });
        $('#j_3 [name="mobilebutton29"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('AddEventHow', {
                        reverse: false
                    });
                }
            },
        });
    }
    $("#j_0").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        j_0_beforeshow();
    });
    if (runBeforeShow) {
        j_0_beforeshow();
    } else {
        j_0_onLoad();
    }
}
$("#j_0").die("pageinit").live("pageinit", function(event, ui) {
    Tiggzi.processSelectMenu($(this));
    j_0_js();
});