/*
 * JS for AddEventHow generated by Tiggzi
 *
 * Created on: Monday, April 15, 2013, 05:30:39 PM (PDT)
 */
/************************************
 * JS API provided by Exadel Tiggzi  *
 ************************************/
/* Setting project environment indicator */
Tiggzi.env = "bundle";
Tiggzi.getProjectGUID = function() {
    return '46d01e13-5e39-4d93-81d0-c3d4c5617e10';
}
Tiggzi.getTargetPlatform = function() {
    return '0';
}

function navigateTo(outcome, useAjax) {
    Tiggzi.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Tiggzi.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Tiggzi.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Tiggzi.setDetailContent(pageUrl);
}
/**********************
 * SECURITY CONTEXTS  *
 **********************/
/*******************************
 *      SERVICE SETTINGS        *
 ********************************/
/*************************
 *      SERVICES          *
 *************************/
var GetToken = new Tiggr.RestService({
    'url': 'https://graph.facebook.com/oauth/access_token',
    'dataType': 'json',
    'type': 'get',
});
var RESTService = new Tiggr.RestService({
    'url': 'http://study-api.herokuapp.com/api/notices',
    'dataType': 'json',
    'type': 'post',
    'contentType': 'application/json',
});
var GetData = new Tiggr.RestService({
    'url': 'https://graph.facebook.com/me',
    'dataType': 'json',
    'type': 'get',
});
var Camera_service = new Tiggr.CameraService({});
createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
Tiggzi.AppPages = [{
    "name": "AddEventWhat",
    "location": "AddEventWhat.html"
}, {
    "name": "AddEventWhen",
    "location": "AddEventWhen.html"
}, {
    "name": "FinishedCreating",
    "location": "FinishedCreating.html"
}, {
    "name": "AddEventHow",
    "location": "AddEventHow.html"
}, {
    "name": "Result",
    "location": "Result.html"
}, {
    "name": "whatwhatwhat",
    "location": "whatwhatwhat.html"
}, {
    "name": "AddEventWho",
    "location": "AddEventWho.html"
}, {
    "name": "whowhowho",
    "location": "whowhowho.html"
}, {
    "name": "howhowhow1",
    "location": "howhowhow1.html"
}, {
    "name": "Login",
    "location": "Login.html"
}, {
    "name": "whenwhenwhen",
    "location": "whenwhenwhen.html"
}, {
    "name": "Home",
    "location": "Home.html"
}];
j_94_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel6': 'j_98',
        'mobiletextinput12': 'j_99',
        'mobilespacer8': 'j_100',
        'mobilelabel7': 'j_101',
        'mobiletextarea2': 'j_102',
        'mobilespacer9': 'j_103',
        'mobilelabel16': 'j_104',
        'mobiletextarea8': 'j_105',
        'mobilespacer10': 'j_106',
        'mobilelabel18': 'j_107',
        'mobiletextarea11': 'j_108',
        'mobilebutton30': 'j_109',
        'mobilebutton33': 'j_110',
        'mobilebutton35': 'j_111',
        'mobilelabel16': 'j_112'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    Tiggr.CurrentScreen = 'j_94';
    /*************************
     * NONVISUAL COMPONENTS  *
     *************************/
    var datasources = [];
    // Tiggzi Push-notification registration service
    /************************
     * EVENTS AND HANDLERS  *
     ************************/
    j_94_beforeshow = function() {
        Tiggzi.CurrentScreen = 'j_94';
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }
    // screen onload
    screen_86B4_onLoad = j_94_onLoad = function() {
        screen_86B4_elementsExtraJS();
        j_94_windowEvents();
        screen_86B4_elementsEvents();
    }
    // screen window events
    screen_86B4_windowEvents = j_94_windowEvents = function() {
        $('#j_94').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });
        $('#j_94').bind({
            swipeleft: function() {
                Tiggr.navigateTo('AddEventWho', {
                    transition: 'slide',
                    reverse: false
                });
            },
            swiperight: function() {
                Tiggr.navigateTo('AddEventHow', {
                    transition: 'slide',
                    reverse: false
                });
                Tiggr.navigateTo('AddEventWhen', {
                    transition: 'slide',
                    reverse: false
                });
            },
        });
    }
    // screen elements extra js
    screen_86B4_elementsExtraJS = j_94_elementsExtraJS = function() {
        // screen (screen-86B4) extra code
    }
    // screen elements handler
    screen_86B4_elementsEvents = j_94_elementsEvents = function() {
        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });
        $('#j_97 [name="mobiletextinput12"]').die().live({
            input: function() {
                setVar_('goal', 'j_99', 'text', '', this);
            },
        });
        $('#j_97 [name="mobiletextarea2"]').die().live({
            input: function() {
                setVar_('schedule', 'j_102', 'text', '', this);
            },
        });
        $('#j_97 [name="mobiletextarea8"]').die().live({
            input: function() {
                setVar_('available', 'j_105', 'text', '', this);
            },
        });
        $('#j_97 [name="mobiletextarea11"]').die().live({
            input: function() {
                setVar_('needs', 'j_108', 'text', '', this);
            },
        });
        $('#j_97 [name="mobilebutton30"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('AddEventWhen', {
                        reverse: false
                    });
                }
            },
        });
        $('#j_97 [name="mobilebutton33"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('Home', {
                        reverse: false
                    });
                }
            },
        });
        $('#j_97 [name="mobilebutton35"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('AddEventWhat', {
                        reverse: false
                    });
                }
            },
        });
    }
    $("#j_94").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        j_94_beforeshow();
    });
    if (runBeforeShow) {
        j_94_beforeshow();
    } else {
        j_94_onLoad();
    }
}
$("#j_94").die("pageinit").live("pageinit", function(event, ui) {
    Tiggzi.processSelectMenu($(this));
    j_94_js();
});