/*
 * JS for Home generated by Tiggzi
 *
 * Created on: Monday, April 15, 2013, 05:30:39 PM (PDT)
 */
/************************************
 * JS API provided by Exadel Tiggzi  *
 ************************************/
/* Setting project environment indicator */
Tiggzi.env = "bundle";
Tiggzi.getProjectGUID = function() {
    return '46d01e13-5e39-4d93-81d0-c3d4c5617e10';
}
Tiggzi.getTargetPlatform = function() {
    return '0';
}

function navigateTo(outcome, useAjax) {
    Tiggzi.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Tiggzi.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Tiggzi.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Tiggzi.setDetailContent(pageUrl);
}
/**********************
 * SECURITY CONTEXTS  *
 **********************/
/*******************************
 *      SERVICE SETTINGS        *
 ********************************/
/*************************
 *      SERVICES          *
 *************************/
var GetToken = new Tiggr.RestService({
    'url': 'https://graph.facebook.com/oauth/access_token',
    'dataType': 'json',
    'type': 'get',
});
var RESTService = new Tiggr.RestService({
    'url': 'http://study-api.herokuapp.com/api/notices',
    'dataType': 'json',
    'type': 'post',
    'contentType': 'application/json',
});
var GetData = new Tiggr.RestService({
    'url': 'https://graph.facebook.com/me',
    'dataType': 'json',
    'type': 'get',
});
var Camera_service = new Tiggr.CameraService({});
createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
Tiggzi.AppPages = [{
    "name": "AddEventWhat",
    "location": "AddEventWhat.html"
}, {
    "name": "AddEventWhen",
    "location": "AddEventWhen.html"
}, {
    "name": "FinishedCreating",
    "location": "FinishedCreating.html"
}, {
    "name": "AddEventHow",
    "location": "AddEventHow.html"
}, {
    "name": "Result",
    "location": "Result.html"
}, {
    "name": "whatwhatwhat",
    "location": "whatwhatwhat.html"
}, {
    "name": "AddEventWho",
    "location": "AddEventWho.html"
}, {
    "name": "whowhowho",
    "location": "whowhowho.html"
}, {
    "name": "howhowhow1",
    "location": "howhowhow1.html"
}, {
    "name": "Login",
    "location": "Login.html"
}, {
    "name": "whenwhenwhen",
    "location": "whenwhenwhen.html"
}, {
    "name": "Home",
    "location": "Home.html"
}];
j_244_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobileimage11': 'j_248',
        'mobilelabel3': 'j_249',
        'mobilelabel3': 'j_250',
        'mobilecheckboxgroup2': 'j_251',
        'mobilecheckbox6': 'j_252',
        'mobilecheckbox7': 'j_253',
        'mobilecheckbox8': 'j_254',
        'mobilelabel2': 'j_255',
        'mobilecheckboxgroup1': 'j_256',
        'mobilecheckbox1': 'j_257',
        'mobilecheckbox6': 'j_258',
        'mobilecheckbox7': 'j_259',
        'mobilecheckbox8': 'j_260',
        'mobilecheckbox9': 'j_261',
        'mobilespacer12': 'j_262',
        'mobilespacer22': 'j_263',
        'mobilebutton4': 'j_264',
        'mobilebutton10': 'j_265'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    Tiggr.CurrentScreen = 'j_244';
    /*************************
     * NONVISUAL COMPONENTS  *
     *************************/
    var datasources = [];
    // Tiggzi Push-notification registration service
    /************************
     * EVENTS AND HANDLERS  *
     ************************/
    j_244_beforeshow = function() {
        Tiggzi.CurrentScreen = 'j_244';
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }
    // screen onload
    screen_97F9_onLoad = j_244_onLoad = function() {
        screen_97F9_elementsExtraJS();
        j_244_windowEvents();
        screen_97F9_elementsEvents();
    }
    // screen window events
    screen_97F9_windowEvents = j_244_windowEvents = function() {
        $('#j_244').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });
    }
    // screen elements extra js
    screen_97F9_elementsExtraJS = j_244_elementsExtraJS = function() {
        // screen (screen-97F9) extra code
    }
    // screen elements handler
    screen_97F9_elementsEvents = j_244_elementsEvents = function() {
        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });
        $('#j_247 [name="mobilebutton4"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('whatwhatwhat', {
                        transition: 'flip',
                        reverse: false
                    });
                }
            },
        });
        $('#j_247 [name="mobilebutton10"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('Home', {
                        transition: 'flip',
                        reverse: false
                    });
                }
            },
        });
    }
    $("#j_244").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        j_244_beforeshow();
    });
    if (runBeforeShow) {
        j_244_beforeshow();
    } else {
        j_244_onLoad();
    }
}
$("#j_244").die("pageinit").live("pageinit", function(event, ui) {
    Tiggzi.processSelectMenu($(this));
    j_244_js();
});