/*
 * JS for howhowhow1 generated by Tiggzi
 *
 * Created on: Monday, April 15, 2013, 05:30:39 PM (PDT)
 */
/************************************
 * JS API provided by Exadel Tiggzi  *
 ************************************/
/* Setting project environment indicator */
Tiggzi.env = "bundle";
Tiggzi.getProjectGUID = function() {
    return '46d01e13-5e39-4d93-81d0-c3d4c5617e10';
}
Tiggzi.getTargetPlatform = function() {
    return '0';
}

function navigateTo(outcome, useAjax) {
    Tiggzi.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Tiggzi.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Tiggzi.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Tiggzi.setDetailContent(pageUrl);
}
/**********************
 * SECURITY CONTEXTS  *
 **********************/
/*******************************
 *      SERVICE SETTINGS        *
 ********************************/
/*************************
 *      SERVICES          *
 *************************/
var GetToken = new Tiggr.RestService({
    'url': 'https://graph.facebook.com/oauth/access_token',
    'dataType': 'json',
    'type': 'get',
});
var RESTService = new Tiggr.RestService({
    'url': 'http://study-api.herokuapp.com/api/notices',
    'dataType': 'json',
    'type': 'post',
    'contentType': 'application/json',
});
var GetData = new Tiggr.RestService({
    'url': 'https://graph.facebook.com/me',
    'dataType': 'json',
    'type': 'get',
});
var Camera_service = new Tiggr.CameraService({});
createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
Tiggzi.AppPages = [{
    "name": "AddEventWhat",
    "location": "AddEventWhat.html"
}, {
    "name": "AddEventWhen",
    "location": "AddEventWhen.html"
}, {
    "name": "FinishedCreating",
    "location": "FinishedCreating.html"
}, {
    "name": "AddEventHow",
    "location": "AddEventHow.html"
}, {
    "name": "Result",
    "location": "Result.html"
}, {
    "name": "whatwhatwhat",
    "location": "whatwhatwhat.html"
}, {
    "name": "AddEventWho",
    "location": "AddEventWho.html"
}, {
    "name": "whowhowho",
    "location": "whowhowho.html"
}, {
    "name": "howhowhow1",
    "location": "howhowhow1.html"
}, {
    "name": "Login",
    "location": "Login.html"
}, {
    "name": "whenwhenwhen",
    "location": "whenwhenwhen.html"
}, {
    "name": "Home",
    "location": "Home.html"
}];
j_182_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel56': 'j_186',
        'mobiletextinput33': 'j_187',
        'mobilespacer25': 'j_188',
        'mobilelabel60': 'j_189',
        'mobiletextarea25': 'j_190',
        'mobilespacer29': 'j_191',
        'mobilelabel50': 'j_192',
        'mobiletextarea23': 'j_193',
        'mobilespacer27': 'j_194',
        'mobilelabel58': 'j_195',
        'mobiletextarea21': 'j_196',
        'mobilespacer9': 'j_197',
        'mobilegrid9': 'j_198',
        'mobilegridcell129': 'j_199',
        'mobilebutton65': 'j_200',
        'mobilegridcell130': 'j_201',
        'mobilebutton68': 'j_202',
        'mobilegridcell141': 'j_203',
        'mobilebutton71': 'j_204'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    Tiggr.CurrentScreen = 'j_182';
    /*************************
     * NONVISUAL COMPONENTS  *
     *************************/
    var datasources = [];
    restservice5 = new Tiggr.DataSource(RESTService, {
        'onComplete': function(jqXHR, textStatus) {
            $t.refreshScreenFormElements("j_182");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [],
        'requestMapping': [{
            'PATH': ['emails'],
            'ATTR': 'faejdb'
        }, {
            'PATH': ['title'],
            'ATTR': 'fdasfda'
        }, {
            'PATH': ['subject'],
            'ATTR': 'fadfad'
        }, {
            'PATH': ['description'],
            'ATTR': 'fdasfdasf'
        }, {
            'PATH': ['date'],
            'ATTR': 'fdsaf'
        }, {
            'PATH': ['start_time'],
            'ATTR': 'fadsfasd'
        }, {
            'PATH': ['end_time'],
            'ATTR': 'fdsf'
        }, {
            'PATH': ['location'],
            'ATTR': 'fadsfds'
        }, {
            'PATH': ['goal'],
            'ID': '___local_storage___',
            'ATTR': 'goal'
        }, {
            'PATH': ['resources_needed'],
            'ID': '___local_storage___',
            'ATTR': 'needs'
        }, {
            'PATH': ['resources_available'],
            'ID': '___local_storage___',
            'ATTR': 'available'
        }, {
            'PATH': ['agenda'],
            'ID': '___local_storage___',
            'ATTR': 'schedule'
        }]
    });
    datasources.push(restservice5);
    // Tiggzi Push-notification registration service
    /************************
     * EVENTS AND HANDLERS  *
     ************************/
    j_182_beforeshow = function() {
        Tiggzi.CurrentScreen = 'j_182';
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }
    // screen onload
    screen_6E5E_onLoad = j_182_onLoad = function() {
        screen_6E5E_elementsExtraJS();
        j_182_windowEvents();
        screen_6E5E_elementsEvents();
    }
    // screen window events
    screen_6E5E_windowEvents = j_182_windowEvents = function() {
        $('#j_182').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });
    }
    // screen elements extra js
    screen_6E5E_elementsExtraJS = j_182_elementsExtraJS = function() {
        // screen (screen-6E5E) extra code
    }
    // screen elements handler
    screen_6E5E_elementsEvents = j_182_elementsEvents = function() {
        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });
        $('#j_185 [name="mobiletextinput33"]').die().live({
            input: function() {
                setVar_('goal', 'j_187', 'text', '', this);
            },
        });
        $('#j_185 [name="mobiletextarea25"]').die().live({
            input: function() {
                setVar_('needs', 'j_190', 'text', '', this);
            },
        });
        $('#j_185 [name="mobiletextarea23"]').die().live({
            input: function() {
                setVar_('available', 'j_193', 'text', '', this);
            },
        });
        $('#j_185 [name="mobiletextarea21"]').die().live({
            input: function() {
                setVar_('schedule', 'j_196', 'text', '', this);
            },
        });
        $('#j_185 [name="mobilebutton65"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('whatwhatwhat', {
                        transition: 'fade',
                        reverse: false
                    });
                }
            },
        });
        $('#j_185 [name="mobilebutton68"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('Home', {
                        transition: 'flip',
                        reverse: false
                    });
                }
            },
        });
        $('#j_185 [name="mobilebutton71"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('whenwhenwhen', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        });
    }
    $("#j_182").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        j_182_beforeshow();
    });
    if (runBeforeShow) {
        j_182_beforeshow();
    } else {
        j_182_onLoad();
    }
}
$("#j_182").die("pageinit").live("pageinit", function(event, ui) {
    Tiggzi.processSelectMenu($(this));
    j_182_js();
});