/*
 * JS for whenwhenwhen generated by Tiggzi
 *
 * Created on: Monday, April 15, 2013, 05:30:39 PM (PDT)
 */
/************************************
 * JS API provided by Exadel Tiggzi  *
 ************************************/
/* Setting project environment indicator */
Tiggzi.env = "bundle";
Tiggzi.getProjectGUID = function() {
    return '46d01e13-5e39-4d93-81d0-c3d4c5617e10';
}
Tiggzi.getTargetPlatform = function() {
    return '0';
}

function navigateTo(outcome, useAjax) {
    Tiggzi.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Tiggzi.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Tiggzi.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Tiggzi.setDetailContent(pageUrl);
}
/**********************
 * SECURITY CONTEXTS  *
 **********************/
/*******************************
 *      SERVICE SETTINGS        *
 ********************************/
/*************************
 *      SERVICES          *
 *************************/
var GetToken = new Tiggr.RestService({
    'url': 'https://graph.facebook.com/oauth/access_token',
    'dataType': 'json',
    'type': 'get',
});
var RESTService = new Tiggr.RestService({
    'url': 'http://study-api.herokuapp.com/api/notices',
    'dataType': 'json',
    'type': 'post',
    'contentType': 'application/json',
});
var GetData = new Tiggr.RestService({
    'url': 'https://graph.facebook.com/me',
    'dataType': 'json',
    'type': 'get',
});
var Camera_service = new Tiggr.CameraService({});
createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
Tiggzi.AppPages = [{
    "name": "AddEventWhat",
    "location": "AddEventWhat.html"
}, {
    "name": "AddEventWhen",
    "location": "AddEventWhen.html"
}, {
    "name": "FinishedCreating",
    "location": "FinishedCreating.html"
}, {
    "name": "AddEventHow",
    "location": "AddEventHow.html"
}, {
    "name": "Result",
    "location": "Result.html"
}, {
    "name": "whatwhatwhat",
    "location": "whatwhatwhat.html"
}, {
    "name": "AddEventWho",
    "location": "AddEventWho.html"
}, {
    "name": "whowhowho",
    "location": "whowhowho.html"
}, {
    "name": "howhowhow1",
    "location": "howhowhow1.html"
}, {
    "name": "Login",
    "location": "Login.html"
}, {
    "name": "whenwhenwhen",
    "location": "whenwhenwhen.html"
}, {
    "name": "Home",
    "location": "Home.html"
}];
j_208_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'now': 'j_212',
        'mobilespacer10': 'j_213',
        'mobilelabel48': 'j_214',
        'mobiletextinput24': 'j_215',
        'mobilespacer11': 'j_216',
        'mobilelabel51': 'j_217',
        'mobiletextinput30': 'j_218',
        'mobilebutton62': 'j_219',
        'googlemap4': 'j_220',
        'marker1': 'j_221',
        'markeroptions2': 'j_222',
        'mobilespacer12': 'j_223',
        'mobilegrid8': 'j_224',
        'mobilegridcell111': 'j_225',
        'mobilebutton53': 'j_226',
        'mobilegridcell112': 'j_227',
        'mobilebutton56': 'j_228',
        'mobilegridcell123': 'j_229',
        'mobilebutton59': 'j_230'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    Tiggr.CurrentScreen = 'j_208';
    /*************************
     * NONVISUAL COMPONENTS  *
     *************************/
    var datasources = [];
    restservice6 = new Tiggr.DataSource(RESTService, {
        'onComplete': function(jqXHR, textStatus) {
            $t.refreshScreenFormElements("j_208");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [],
        'requestMapping': [{
            'PATH': ['emails'],
            'ATTR': 'vivekkls@gmail.com\t'
        }, {
            'PATH': ['title'],
            'ATTR': 'Chemistry Party'
        }, {
            'PATH': ['subject'],
            'ATTR': 'Chemistry'
        }, {
            'PATH': ['description'],
            'ID': '___local_storage___',
            'ATTR': 'description'
        }, {
            'PATH': ['date'],
            'ID': '___local_storage___',
            'ATTR': 'date'
        }, {
            'PATH': ['start_time'],
            'ID': '___local_storage___',
            'ATTR': 'start'
        }, {
            'PATH': ['end_time'],
            'ID': '___local_storage___',
            'ATTR': 'end'
        }, {
            'PATH': ['location'],
            'ID': '___local_storage___',
            'ATTR': 'location'
        }, {
            'PATH': ['goal'],
            'ID': '___local_storage___',
            'ATTR': 'goal'
        }, {
            'PATH': ['resources_needed'],
            'ID': '___local_storage___',
            'ATTR': 'needs'
        }, {
            'PATH': ['resources_available'],
            'ID': '___local_storage___',
            'ATTR': 'available'
        }, {
            'PATH': ['agenda'],
            'ID': '___local_storage___',
            'ATTR': 'schedule'
        }]
    });
    datasources.push(restservice6);
    // Tiggzi Push-notification registration service
    /************************
     * EVENTS AND HANDLERS  *
     ************************/
    j_208_beforeshow = function() {
        Tiggzi.CurrentScreen = 'j_208';
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }
    // screen onload
    screen_5797_onLoad = j_208_onLoad = function() {
        screen_5797_elementsExtraJS();
        j_208_windowEvents();
        screen_5797_elementsEvents();
    }
    // screen window events
    screen_5797_windowEvents = j_208_windowEvents = function() {
        $('#j_208').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });
    }
    // screen elements extra js
    screen_5797_elementsExtraJS = j_208_elementsExtraJS = function() {
        // screen (screen-5797) extra code
        /* now */
        mobiledatepicker2_selector = "#j_212";
        mobiledatepicker2_dataPickerOptions = {
            dateFormat: "mm/dd/yy",
            firstDay: 0,
            dayNamesMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
            monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
            showOtherMonths: true
        };
        Tiggzi.__registerComponent('now', new Tiggzi.TiggziMobileDatePickerComponent("j_212", mobiledatepicker2_dataPickerOptions)); /* googlemap4 */
        var googlemap4_options = {
            markerSourceName: "googlemap4_markers",
            latitude: "37.443",
            longitude: "-122.158",
            address: "",
            zoom: 10,
            showLocationMarker: false
        }
        Tiggzi.__registerComponent('googlemap4', new Tiggzi.TiggziMapComponent("googlemap4", googlemap4_options));
        $("[name='googlemap4']").closest("[data-role='page']").bind({
            pageshow: function() {
                if (Tiggzi('googlemap4') != undefined) {
                    Tiggzi('googlemap4').refresh();
                }
            }
        }); /* markeroptions2 */
        $("#j_222").attr("reRender", "googlemap4");
    }
    // screen elements handler
    screen_5797_elementsEvents = j_208_elementsEvents = function() {
        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });
        $('#j_211 [name="mobiletextinput24"]').die().live({
            input: function() {
                setVar_('start', 'j_215', 'text', '', this);
            },
        });
        $('#j_211 [name="mobiletextinput30"]').die().live({
            input: function() {
                setVar_('location', 'j_218', 'text', '', this);
            },
        });
        $('#j_211 [name="mobilebutton53"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('howhowhow1', {
                        transition: 'fade',
                        reverse: false
                    });
                }
            },
        });
        $('#j_211 [name="mobilebutton56"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('Home', {
                        transition: 'flip',
                        reverse: false
                    });
                }
            },
        });
        $('#j_211 [name="mobilebutton59"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    var dateObject = Tiggzi('now');
                    var date = dateObject.datepicker_dataPickerOptions.defaultDate;
                    localStorage.setItem('date', date);
                    Tiggr.navigateTo('whowhowho', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        });
    }
    $("#j_208").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        j_208_beforeshow();
    });
    if (runBeforeShow) {
        j_208_beforeshow();
    } else {
        j_208_onLoad();
    }
}
$("#j_208").die("pageinit").live("pageinit", function(event, ui) {
    Tiggzi.processSelectMenu($(this));
    j_208_js();
});